version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pa55word!
      POSTGRES_DB: swim-store
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


