version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pa55w0rd!
      POSTGRES_DB: swimstoredb
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


